POST http://localhost:3000/api/taza HTTP/1.1
Content-Type: application/json

{
    "id_tipo": 2,
    "color": "Verde",
    "dimensiones": "150",
    "capacidad": "500",
    "modelo": "AAGY-3",
    "material": "Vidrio",
    "piezas": 40
}

GET http://localhost:3000/api/taza/all HTTP/1.1